# Generated by Django 5.2.14 on 2026-06-10 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
        ('usuarios', '0007_sucursal_departamento_sucursal_numero_telefono'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='insumo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='insumo',
            name='unidad_medida',
            field=models.CharField(choices=[('unidad', 'Unidad'), ('caja', 'Caja'), ('frasco', 'Frasco'), ('kit', 'Kit'), ('ml', 'Mililitros'), ('l', 'Litros'), ('g', 'Gramos'), ('mg', 'Miligramos'), ('tubo', 'Tubo'), ('otro', 'Otro')], default='unidad', max_length=20),
        ),
        migrations.AddField(
            model_name='inventario',
            name='nombreInventario',
            field=models.CharField(default='Inventario principal', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.sucursal'),
        ),
        migrations.AlterUniqueTogether(
            name='iteminventario',
            unique_together={('insumo', 'inventario')},
        ),
        migrations.AddField(
            model_name='insumo',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='insumos', to='inventario.categoriainsumo'),
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('ajuste', 'Ajuste')], max_length=10)),
                ('cantidad', models.PositiveIntegerField()),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('item_inventario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='inventario.iteminventario')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
