# Generated by Django 5.2.14 on 2026-06-10 03:40

from django.db import migrations

def crear_categorias(apps, schema_editor):
    CategoriaInsumo = apps.get_model(
        'inventario',
        'CategoriaInsumo'
    )

    categorias = [
        'Reactivos',
        'Material de Laboratorio',
        'Equipo de Protección Personal',
        'Material de Limpieza',
        'Kits Diagnósticos',
        'Papelería',
        'Otros',
    ]

    for nombre in categorias:
        CategoriaInsumo.objects.get_or_create(
            nombre=nombre
        )

class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_categoriainsumo_insumo_activo_insumo_unidad_medida_and_more'),
    ]

    operations = [
        migrations.RunPython(
            crear_categorias
        ),
    ]
