# Generated by Django 5.2.14 on 2026-05-12 03:07

from django.db import migrations

#CREACION DE GRUPOS 
def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')

    groups = ['Recepcionistas', 'Laboratoristas', 'Almacenistas']

    for name in groups:
        Group.objects.get_or_create(name=name)

#función que revierte (elimina) la migraxion
def delete_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    groups = ['Recepcionistas', 'Laboratoristas', 'Almacenistas']
    Group.objects.filter(name__in=groups).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_sucursal'),
    ]

    operations = [
        migrations.RunPython(create_groups, reverse_code=delete_groups),
    ]
