# Generated by Django 5.2.14 on 2026-05-28 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_auto_20260512_0307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rol',
            name='nombre',
            field=models.CharField(choices=[('LAB', 'laboratorista'), ('REC', 'recepcionista'), ('INV', 'almacenista'), ('CLI', 'cliente')], max_length=5),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to='usuarios.sucursal'),
        ),
    ]
