# Generated by Django 5.2.14 on 2026-05-28 21:35
from django.db import migrations

def crear_roles_predeterminados(apps, schema_editor):
    Rol = apps.get_model('usuarios', 'Rol')    
    roles = ['LAB', 'REC', 'INV', 'CLI']
    
    for codigo in roles:
        Rol.objects.get_or_create(nombre=codigo)

def eliminar_roles(apps, schema_editor):
    Rol = apps.get_model('usuarios', 'Rol')
    Rol.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_rol_nombre_alter_usuario_sucursal'),
    ]

    operations = [
        migrations.RunPython(crear_roles_predeterminados, reverse_code=eliminar_roles),
    ]

