# Generated by Django 5.2.14 on 2026-06-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_popular_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='departamento',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='numero_telefono',
            field=models.CharField(default='', max_length=8, null=True),
        ),
    ]
