# Generated by Django 5.2.14 on 2026-06-11 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_sucursal_departamento_sucursal_numero_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='ubicacion',
            field=models.CharField(max_length=150),
        ),
    ]
