# Generated by Django 6.0.5 on 2026-05-31 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0004_grupo_clientes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreD', models.CharField(max_length=100)),
                ('jvpm', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ParametroDefinicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreP', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=10)),
                ('valorNorma', models.CharField(max_length=25)),
                ('unidadMedida', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='TipoExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('especial', models.BooleanField(default=False)),
                ('parametros', models.ManyToManyField(to='examenes.parametrodefinicion')),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encabezado', models.CharField(max_length=100)),
                ('correlativo', models.IntegerField()),
                ('fechaEmision', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='examenes.doctor')),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.expediente')),
                ('examenes', models.ManyToManyField(to='examenes.tipoexamen')),
            ],
        ),
    ]
