# Generated by Django 6.0.5 on 2026-05-31 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('completado', models.BooleanField(default=False)),
                ('tipoFecha', models.CharField(max_length=20)),
                ('orden', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='examenes.orden')),
            ],
        ),
    ]
