# Generated by Django 6.0.5 on 2026-05-31 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0002_pagos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagos',
            old_name='tipoFecha',
            new_name='tipo_pago',
        ),
    ]
