# Generated by Django 6.0.5 on 2026-06-02 00:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0003_rename_tipofecha_pagos_tipo_pago'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='examenes',
        ),
        migrations.RemoveField(
            model_name='tipoexamen',
            name='parametros',
        ),
        migrations.AddField(
            model_name='parametrodefinicion',
            name='tipo_examen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='parametros', to='examenes.tipoexamen'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ExamenRealizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaRealizado', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('completado', 'Completado'), ('entregado', 'Entregado')], default='pendiente', max_length=25)),
                ('observaciones', models.CharField(blank=True, max_length=500, null=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='examenes.orden')),
                ('procesado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tipo_examen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='examenes.tipoexamen')),
            ],
        ),
        migrations.CreateModel(
            name='ReporteClinicoPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('consecutivo', models.CharField(max_length=50)),
                ('observaciones', models.CharField(blank=True, max_length=500, null=True)),
                ('encabezado', models.CharField(blank=True, max_length=100, null=True)),
                ('generado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_generados', to=settings.AUTH_USER_MODEL)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reportes', to='examenes.orden')),
            ],
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(blank=True, max_length=50, null=True)),
                ('examen_realizado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='examenes.examenrealizado')),
                ('parametro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='examenes.parametrodefinicion')),
            ],
        ),
    ]
