# Generated by Django 6.0.5 on 2026-06-02 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0004_remove_orden_examenes_remove_tipoexamen_parametros_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReporteClinicoPDF',
        ),
    ]
