# Generated by Django 5.2.14 on 2026-06-03 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0004_remove_orden_examenes_remove_tipoexamen_parametros_and_more'),
        ('reportesPDF', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoexamen',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reportesPDF.configuracionreporte'),
        ),
        migrations.AddField(
            model_name='tipoexamen',
            name='perfil',
            field=models.CharField(blank=True, choices=[('QSAN', 'QUIMICA SANGUÍNEA'), ('QURI', 'QUIMICA URINARIA'), ('ELEC', 'ELECTROLITOS'), ('HEMA', 'HEMATOLOGIA'), ('COAG', 'COAGULACIÓN'), ('ENDO', 'ENDOCRINOLOGÍA'), ('INMU', 'INMUNOLOGÍA'), ('MICR', 'MICROBIOLOGÍA'), ('PESP', 'PRUEBAS ESPECIALES'), ('MTUM', 'MARCADORES TUMORALES'), ('MCAR', 'MARCADORES CARDÍACOS'), ('NSRE', 'NIVELES SÉRICOS'), ('BMOL', 'BIOLOGÍA MOLECULAR'), ('UROA', 'UROANÁLISIS'), ('COPR', 'COPROLOGÍA'), ('DORO', 'DROGAS EN ORINA'), ('DTER', 'DROGAS TERAPÉUTICAS'), ('IMGL', 'INMUNOGLOBULINAS')], max_length=100, null=True),
        ),
    ]
