# Generated by Django 5.2.14 on 2026-06-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0005_tipoexamen_categoria_tipoexamen_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='fechaEmision',
            field=models.DateField(),
        ),
    ]
