# Generated by Django 6.0.5 on 2026-06-02 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0005_delete_reporteclinicopdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='fechaEmision',
            field=models.DateField(auto_now_add=True),
        ),
    ]
