# Generated by Django 5.2.14 on 2026-06-03 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0006_alter_orden_fechaemision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orden',
            name='encabezado',
        ),
    ]
