# Generated by Django 6.0.5 on 2026-06-03 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0006_alter_orden_fechaemision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orden',
            name='correlativo',
            field=models.IntegerField(max_length=10),
        ),
    ]
