# Generated by Django 5.2.14 on 2026-06-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0007_remove_orden_encabezado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametrodefinicion',
            name='tipo',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
