# Generated by Django 5.2.14 on 2026-06-09 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0008_alter_parametrodefinicion_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametrodefinicion',
            name='tipo',
            field=models.CharField(choices=[('NUMER', 'Numérico'), ('POSIT', 'Positivo'), ('NEGAT', 'Negativo'), ('YREAC', 'Reactivo'), ('NREAC', 'No Reactivo'), ('YDETE', 'Detectado'), ('NDETE', 'No Detectado'), ('PRESE', 'Presente'), ('AUSEN', 'Ausente'), ('NORMA', 'Normal'), ('ANORM', 'Anormal'), ('ALTO', 'Alto'), ('BAJO', 'Bajo'), ('CALTO', 'Crítico Alto'), ('CBAJO', 'Crítico Bajo'), ('TRAZA', 'Traza'), ('ESCAS', 'Escaso'), ('MODER', 'Moderado'), ('ABUND', 'Abundante'), ('INDET', 'Indeterminado')], default='NUMER', max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='ReporteClinicoPDF',
        ),
    ]
