# Generated by Django 5.2.14 on 2026-06-09 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0009_alter_parametrodefinicion_tipo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipoexamen',
            name='categoria',
        ),
        migrations.AddField(
            model_name='tipoexamen',
            name='muestra',
            field=models.CharField(blank=True, choices=[('suero', 'Suero'), ('plasma', 'Plasma'), ('sangre_total', 'Sangre Total'), ('sangre_capilar', 'Sangre Capilar'), ('orina', 'Orina'), ('orina_24h', 'Orina 24 Horas'), ('heces', 'Heces'), ('esputo', 'Esputo'), ('semen', 'Semen'), ('hisopado_faringeo', 'Hisopado Faríngeo'), ('hisopado_nasal', 'Hisopado Nasal'), ('exudado_vaginal', 'Exudado Vaginal'), ('exudado_uretral', 'Exudado Uretral'), ('secrecion_herida', 'Secreción de Herida'), ('lcr', 'Líquido Cefalorraquídeo'), ('liquido_pleural', 'Líquido Pleural'), ('liquido_peritoneal', 'Líquido Peritoneal'), ('liquido_sinovial', 'Líquido Sinovial'), ('biopsia', 'Biopsia'), ('otro', 'Otro')], default='suero', max_length=20, null=True),
        ),
    ]
