# Generated by Django 5.2.14 on 2026-06-09 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0010_remove_tipoexamen_categoria_tipoexamen_muestra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametrodefinicion',
            name='tipo',
            field=models.CharField(choices=[('cuant', 'CUANTITATIVO'), ('cuali', 'CUALITATIVO'), ('porc', 'PORCENTUAL'), ('otros', 'OTROS')], default='cuant', max_length=10, null=True),
        ),
    ]
