# Generated by Django 5.2.14 on 2026-06-12 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0011_alter_parametrodefinicion_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='reporte_generado',
            field=models.BooleanField(default=False),
        ),
    ]
