# Generated by Django 5.2.14 on 2026-06-21 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0012_orden_reporte_generado'),
        ('usuarios', '0008_alter_sucursal_ubicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.sucursal'),
        ),
    ]
