# Generated by Django 5.2.14 on 2026-06-03 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0004_grupo_clientes'),
        ('examenes', '0004_remove_orden_examenes_remove_tipoexamen_parametros_and_more'),
        ('usuarios', '0007_sucursal_departamento_sucursal_numero_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('TABLA', 'Tabla'), ('CATEGORIZADO', 'Categorizado'), ('IMAGEN', 'Imagen')], max_length=20)),
                ('tipo_examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion', to='examenes.tipoexamen')),
            ],
        ),
        migrations.CreateModel(
            name='ResultadosExamenesPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('correlativo', models.CharField(max_length=50)),
                ('encabezado', models.CharField(blank=True, max_length=600, null=True)),
                ('AnalistaClinico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.registroanalistaclinico')),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_resultados_pdf', to='clientes.expediente')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='examenes.orden')),
            ],
        ),
    ]
