# Generated by Django 5.2.14 on 2026-05-15 21:57

import clientes.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha_nacimiento',
            field=models.DateField(validators=[clientes.models.validar_anio_nacimiento]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='n_dui',
            field=models.CharField(max_length=9, unique=True, validators=[django.core.validators.RegexValidator(code='DUI INVALIDO', message='El número de DUI debe contener exactamente 9 digitos numericos', regex='^\\d{9}$')]),
        ),
    ]
