# Generated by Django 5.2.14 on 2026-05-28 21:22

from django.db import migrations

#CREACION DE GRUPOS 
def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')

    groups = ['Pacientes',]

    for name in groups:
        Group.objects.get_or_create(name=name)

#función que revierte (elimina) la migraxion
def delete_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    groups = ['Pacientes',]
    Group.objects.filter(name__in=groups).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_remove_cliente_apellido_remove_cliente_nombre_and_more'),
    ]

    operations = [
        migrations.RunPython(create_groups, reverse_code=delete_groups),
    ]
